# Generated by Django 4.1.1 on 2022-09-08 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('blog_pic', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('category_1', 'İnsan'), ('category_2', 'Doğa'), ('category_3', 'Yaşam'), ('category_4', 'Sağlık'), ('category_5', 'Teknoloji')], max_length=20)),
                ('status', models.CharField(choices=[('status_1', 'Draft'), ('status_2', 'Published')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
